package ru.rosreestr.ws;

import ru.rosreestr.client.isur.model.CoordinateStatusData;
import ru.rosreestr.client.isur.model.ErrorMessage;
import ru.rosreestr.client.isur.model.ObjectFactory;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebService(name = "isurtestws", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface IService {

    /**
     *
     * @param statusMessage
     */
    @WebMethod(operationName = "SetFilesAndStatus", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/SetFilesAndStatus")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void setFilesAndStatus(
            @WebParam(name = "StatusMessage", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", partName = "StatusMessage")
            CoordinateStatusData statusMessage);


    /**
     *
     * @param parameters
     */
    @WebMethod(operationName = "Acknowledgement", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/Acknowledgement")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void acknowledgement(
            @WebParam(name = "ErrorMessage", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", partName = "parameters")
            ErrorMessage parameters);
}
