//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.05 at 12:30:53 AM AMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://aisercu.rosreestr.ru/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.rosreestr.ws.model;
