
package ru.rosreestr.client.egrip.model;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param request
     * @return
     *     returns ru.mos.asguf.rkis_gu.coordinate.v5.GetRequestListOutMessage
     */
    @WebMethod(operationName = "GetRequestList", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/GetRequestList")
    @WebResult(name = "GetRequestListResult", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/")
    @RequestWrapper(localName = "GetRequestList", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", className = "ru.mos.asguf.rkis_gu.coordinate.v5.GetRequestList")
    @ResponseWrapper(localName = "GetRequestListResponse", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", className = "ru.mos.asguf.rkis_gu.coordinate.v5.GetRequestListResponse")
    public GetRequestListOutMessage getRequestList(
            @WebParam(name = "request", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/")
            GetRequestListInMessage request);

    /**
     * 
     * @param request
     * @return
     *     returns ru.mos.asguf.rkis_gu.coordinate.v5.GetRequestsOutMessage
     */
    @WebMethod(operationName = "GetRequests", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/GetRequests")
    @WebResult(name = "GetRequestsResult", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/")
    @RequestWrapper(localName = "GetRequests", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", className = "ru.mos.asguf.rkis_gu.coordinate.v5.GetRequests")
    @ResponseWrapper(localName = "GetRequestsResponse", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", className = "ru.mos.asguf.rkis_gu.coordinate.v5.GetRequestsResponse")
    public GetRequestsOutMessage getRequests(
            @WebParam(name = "request", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/")
            GetRequestsInMessage request);

    /**
     * 
     * @param message
     */
    @WebMethod(operationName = "SendRequest", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/SendRequest")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void sendRequest(
            @WebParam(name = "Message", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", partName = "Message")
            CoordinateData message);

    /**
     * 
     * @param taskMessage
     */
    @WebMethod(operationName = "SendTask", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/SendTask")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void sendTask(
            @WebParam(name = "TaskMessage", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", partName = "TaskMessage")
            CoordinateTaskData taskMessage);

    /**
     * 
     * @param statusMessage
     */
    @WebMethod(operationName = "SetFilesAndStatus", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/SetFilesAndStatus")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void setFilesAndStatus(
            @WebParam(name = "StatusMessage", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", partName = "StatusMessage")
            CoordinateStatusData statusMessage);

    /**
     * 
     * @param parameters
     */
    @WebMethod(operationName = "Acknowledgement", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/Acknowledgement")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void acknowledgement(
            @WebParam(name = "ErrorMessage", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", partName = "parameters")
            ErrorMessage parameters);

    /**
     * 
     * @param requestsMessage
     */
    @WebMethod(operationName = "SendRequests", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/SendRequests")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void sendRequests(
            @WebParam(name = "RequestsMessage", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", partName = "RequestsMessage")
            ArrayOfCoordinateData requestsMessage);

    /**
     * 
     * @param tasksMessage
     */
    @WebMethod(operationName = "SendTasks", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/SendTasks")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void sendTasks(
            @WebParam(name = "TasksMessage", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", partName = "TasksMessage")
            ArrayOfCoordinateTaskData tasksMessage);

    /**
     * 
     * @param statusesMessage
     */
    @WebMethod(operationName = "SetFilesAndStatuses", action = "http://asguf.mos.ru/rkis_gu/coordinate/v5/SetFilesAndStatuses")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void setFilesAndStatuses(
            @WebParam(name = "StatusesMessage", targetNamespace = "http://asguf.mos.ru/rkis_gu/coordinate/v5/", partName = "StatusesMessage")
            ArrayOfSetFilesAndStatusesData statusesMessage);

}
